image:
  explorer:
    repository: consensys/quorum-explorer
    tag: e175e0b
    pullPolicy: Always #IfNotPresent

resources:
  requests:
    cpu: 1000m
    memory: 1G

# This contains the quorum-dev-quickstart test accounts but can be changed to the generated member accounts or your own choice
explorerConfig: |
  {
  "algorithm": "qbft",
  "nodes": [{
      "name": "validator1",
      "client": "besu",
      "rpcUrl": "http://besu-node-validator-1-0.besu-node-validator-1.besu.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator2",
      "client": "besu",
      "rpcUrl": "http://besu-node-validator-2-0.besu-node-validator-2.besu.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator3",
      "client": "besu",
      "rpcUrl": "http://besu-node-validator-3-0.besu-node-validator-3.besu.svc.cluster.local:8545",
      "privateTxUrl": ""
    },
    {
      "name": "validator4",
      "client": "besu",
      "rpcUrl": "http://besu-node-validator-4-0.besu-node-validator-4.besu.svc.cluster.local:8545",
      "privateTxUrl": ""
    }
  ]
  }

explorerEnvConfig: |-
  QE_BASEPATH="/explorer"
  QE_CONFIG_PATH="/app/config.json"
  NODE_ENV=production

  DISABLE_AUTH=true

  NEXTAUTH_URL=http://localhost:25000
  NEXTAUTH_URL_INTERNAL=http://localhost:25000
  NEXTAUTH_SECRET=d1d28f0fdf4ef6b08ccbac4cd0052b3d

  local_username=
  local_password=

  GITHUB_ID=
  GITHUB_SECRET=

  AUTH0_ID=
  AUTH0_SECRET=
  AUTH0_DOMAIN=

  FACEBOOK_ID=
  FACEBOOK_SECRET=

  GOOGLE_ID=
  GOOGLE_SECRET=

  TWITTER_ID=
  TWITTER_SECRET=

  GITLAB_CLIENT_ID=
  GITLAB_CLIENT_SECRET=

  AZURE_AD_CLIENT_ID=
  AZURE_AD_CLIENT_SECRET=
  AZURE_AD_TENANT_ID=

  ATLASSIAN_CLIENT_ID=
  ATLASSIAN_CLIENT_SECRET=

  COGNITO_CLIENT_ID=
  COGNITO_CLIENT_SECRET=
  COGNITO_ISSUER=

  OKTA_CLIENT_ID=
  OKTA_CLIENT_SECRET=
  OKTA_ISSUER=

  SLACK_CLIENT_ID=
  SLACK_CLIENT_SECRET=
